spring.application.name=Prj3
server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/face_attendance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Regula FaceSDK Web client configuration
# Set to your Regula server base URL, e.g. https://faceapi.regulaforensics.com
regula.facesdk.apiBaseUrl=
server.address=0.0.0.0

